<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>kafka on 被遗忘的博客</title>
    <link>https://wenchao.ren/tags/kafka/</link>
    <description>Recent content in kafka on 被遗忘的博客</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>zh-cn</language>
    <lastBuildDate>Mon, 21 Jan 2019 20:15:33 +0000</lastBuildDate><atom:link href="https://wenchao.ren/tags/kafka/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>kafka listeners &amp; advertised.listeners</title>
      <link>https://wenchao.ren/posts/kafka-listeners-advertised-listeners/</link>
      <pubDate>Mon, 21 Jan 2019 20:15:33 +0000</pubDate>
      
      <guid>https://wenchao.ren/posts/kafka-listeners-advertised-listeners/</guid>
      <description>今天在日常使用spring-kafka消费kafka数据时发现连接不是kafka，出现下面的异常：
2019-01-21 16:55:58,675 WARN wtraceId[] wtracer[] [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] c.w.f.w.k.LogConsumerConfiguration:45 - [wcollect]batch pull data from kafka error java.lang.IllegalStateException: No entry found for connection 30 at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:330) at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:134) at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921) at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287) at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:474) at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:255) at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236) at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1243) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1188) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1164) at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:728) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) at java.util.concurrent.FutureTask.run(FutureTask.java) at java.lang.Thread.run(Thread.java:748)  从上面的异常中大致可以看到是初始化NetworkClient连接时出现问题，基本可以证明是连接不是kafka broker。
后来排查发现是因为我在我本地的代码中是通过ip+port的形式访问的，而我们的kafka broker配置了下面的参数：
############################# Socket Server Settings ############################# # The address the socket server listens on. It will get the value returned from # java.</description>
    </item>
    
  </channel>
</rss>
